### ISSUE TITLE
Package QL does not exist.

### ISSUE THREAD

**Issue by kosbar** [aymanosman/cl-defender#2]
I am newbie in LISP, and have done this commands in row:
pacman -S sbcl (Arch Linux)
curl -O http://beta.quicklisp.org/quicklisp.lisp
sbcl --load quicklisp.lisp
./make.sh

and get this:

> Unhandled SB-C::INPUT-ERROR-IN-LOAD in thread #<SB-THREAD:THREAD tid=588496 "main thread" RUNNING
>  {1001468003}>:
> READ error during LOAD:
> 
>  Package QL does not exist.
> 
>  Line: 5, Column: 13, File-Position: 71
> 
>  Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/kosbar/Projects/cl-missile-command/release.lisp" {1001449243}>
> 
> Backtrace for: #<SB-THREAD:THREAD tid=588496 "main thread" RUNNING {1001468003}>
> 0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-C::INPUT-ERROR-IN-LOAD {1002B3C473}> #<unused argument> :QUIT T)
> 1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-C::INPUT-ERROR-IN-LOAD {1002B3C473}>)
> 2: (INVOKE-DEBUGGER #<SB-C::INPUT-ERROR-IN-LOAD {1002B3C473}>)
> 3: (ERROR #<SB-C::INPUT-ERROR-IN-LOAD {1002B3C473}>)
> 4: (SB-C:COMPILER-ERROR SB-C::INPUT-ERROR-IN-LOAD :CONDITION #<SB-INT:SIMPLE-READER-PACKAGE-ERROR "Package ~A does not exist." {1002B3C423}> :STREAM #<SB-INT:FORM-TRACKING-STREAM for "file /home/kosbar/Projects/cl-missile-command/release.lisp" {1001449243}>)
> 5: (SB-C::%DO-FORMS-FROM-INFO #<FUNCTION (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {7F44135DF4CB}> #<SB-C::SOURCE-INFO {1001455E13}> SB-C::INPUT-ERROR-IN-LOAD)
> 6: (SB-INT:LOAD-AS-SOURCE #<SB-INT:FORM-TRACKING-STREAM for "file /home/kosbar/Projects/cl-missile-command/release.lisp" {1001449243}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
> 7: ((LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) #<SB-INT:FORM-TRACKING-STREAM for "file /home/kosbar/Projects/cl-missile-command/release.lisp" {1001449243}> NIL)
> 8: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) {7F44135DF88B}> #<SB-INT:FORM-TRACKING-STREAM for "file /home/kosbar/Projects/cl-missile-command/release.lisp" {1001449243}> NIL #<SB-INT:FORM-TRACKING-STREAM for "file /home/kosbar/Projects/cl-missile-command/release.lisp" {1001449243}>)
> 9: (LOAD #P"release.lisp" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DEFAULT)
> 10: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:LOAD . "release.lisp") (:QUIT)))
> 11: (SB-IMPL::TOPLEVEL-INIT)
> 12: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
> 13: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
> 14: (SB-IMPL::%START-LISP)
> 
> unhandled condition in --disable-debugger mode, quitting

**Comment by aymanosman** [comment]
You need to load quicklisp after you install it.

Normally, this is done by configuring your init script. See https://www.quicklisp.org/beta/#loading.

You could also do it manually. Try this:

```sh
sbcl --noinform \
     --non-interactive \
     --load ~/quicklisp/setup.lisp \
     --load release.lisp
```

**Comment by kosbar** [comment]
It helps, but next time it downloads something and I get this error:

> To load "raylib":
>   Load 1 ASDF system:
>     raylib
> ; Loading "raylib"
> While evaluating the form starting at line 5, column 0
>   of #P"/home/kosbar/Projects/cl-missile-command/release.lisp":
> Unhandled LOAD-FOREIGN-LIBRARY-ERROR in thread #<SB-THREAD:THREAD tid=14915 "main thread" RUNNING
>                                                   {10048481D3}>:
>   Unable to load foreign library (LIBRAYLIB).
>   Error opening shared object "libraylib.so":
>   libraylib.so: cannot open shared object file: No such file or directory.

In first time it downloads and then was cc building output, but I can't replay this error, cause didn't  remember where it download and build))

**Comment by aymanosman** [comment]
Looks like it can’t find the raylib shared library. I’m guessing you are on Linux since it is looking for the “so”. 

You’ll have to make sure you have raylib installed and sbcl can find it. 

Do you know the full path to the libraylib file?
